### ISSUE TITLE
你好大佬，请教个问题

### ISSUE THREAD

**Issue by fanbingkun** [dengwb1991/owl-ui#2]
大佬，我想问下这种UI框架设计
比如说在packages下面的 button组件  没有看见他引入了 样式文件
那他是在哪里引入了样式
这是怎么做到的...

**Comment by dengwb1991** [comment]
组件样式文件都在 src/styles/ 这个目录里。
我之所以样式与功能分开写，因为方便我管理，结构清晰。
在示例里（npm run dev）有引入总的样式文件，文件路径 /examples/app.vue 。
